name: pikachu
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.8

dependencies:
  app_links: ^7.0.0
  cached_network_image: ^3.4.1
  crypto: ^3.0.7
  dio: ^5.9.1
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.2.0
  flutter_secure_storage: ^10.0.0
  flutter_staggered_grid_view: ^0.7.0
  flutter_widget_from_html: ^0.17.1
  shared_preferences: ^2.5.4
  url_launcher: ^6.3.2
  webview_flutter: ^4.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
